version: '3.9'
services:
  iyp_loader:
    image: neo4j/neo4j-admin:5.16.0
    profiles: ["local", "public_tls", "public_notls"]
    container_name: iyp_loader
    tty: true
    stdin_open: true
    volumes:
      - ./data:/data
      - ./dumps:/dumps
      - ./backups:/backups
    command: neo4j-admin database load neo4j --from-path=/dumps --verbose

  iyp:
    image: neo4j:5.16.0
    profiles: ["local"]
    container_name: iyp
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
    depends_on:
      iyp_loader:
        condition: service_completed_successfully

  iyp_readonly_tls:
    image: neo4j:5.16.0
    profiles: ["public_tls"]
    container_name: iyp
    restart: unless-stopped
    ports:
      - 7473:7473
      - 7687:7687
    volumes:
      - ./data:/data
      - ./public/certificates:/ssl
      - ./public/conf_tls:/conf
      - ./public/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password
    depends_on:
      iyp_loader:
        condition: service_completed_successfully

  iyp_readonly_notls:
    image: neo4j:5.16.0
    profiles: ["public_notls"]
    container_name: iyp
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data:/data
      - ./public/conf_notls:/conf
      - ./public/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/password
    depends_on:
      iyp_loader:
        condition: service_completed_successfully
